# Site settings
title: HGHMN
tagline: "Nathan Hughes"
url: "https://hghmn.com"
repository: hghmn/hghmn.github.io

# Social (not very, though)
github: hghmn
twitter: hghmn
instagram: hghmn

exclude: [README.md]
